### ISSUE TITLE
Configuration resets after update

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [YunoHost-Apps/simple-torrent_ynh#18]
After updating, the configuration made through the web UI goes back to default, eg. the seed ratio goes back to 0.

**Versions**
- Hardware: *ARM instance at Scaleway*
- YunoHost version: 4.1.7.3
- I have access to my server: *Through SSH | through the webadmin*
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: *no*
- Using, or trying to install package version/branch: stable
- If upgrading, current package version: *current : 1.2.15~ynh1*. As far as I remember, every updates since I'm using this app (November 2020) triggers this issue.

**To Reproduce**
1. Install simple-torrent
2. Change configuration through webUI
3. When an update is available, update : configuration is lost.

**Expected behavior**
Configuration should remain untouched : backup & restore the configuration file ?

Note this is a minor issue, and thanks for your work!
Cheers

**Comment by ericgaspar** [comment]
Closing. Should be fexed with #20
