### ISSUE TITLE
Error while installing simple-torrent

### ISSUE THREAD

**Issue by Omnia89** [YunoHost-Apps/simple-torrent_ynh#26]
**How to post a meaningful bug report**
1. *Read this whole template first.*
2. *Determine if you are on the right place:*
   - *If you were performing an action on the app from the webadmin or the CLI (install, update, backup, restore, change_url...), you are on the right place!*
   - *Otherwise, the issue may be due to Simple Torrent itself. Refer to its documentation or repository for help.*
   - *If you have a doubt, post here, we will figure it out together.*
3. *Delete the italic comments as you write over them below, and remove this guide.*
--- 

**Describe the bug**
I've tried to intall simple-torrent, first without removing transmission, and then after removing it, but the error shown its the same and it doesn't end the installation.

**Versions**
- Hardware: Cubox i4-pro, Armbian 21.02.3 Buster with Linux 5.10.21-imx6
- YunoHost version: 4.1.7.4
- I have access to my server: SSH and webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance ?: maybe?
  I installed manually over an already existent armbian (fresh install)
- Using, or trying to install package version/branch: main version
- If upgrading, current package version: 

**To Reproduce**
- Access webadmin
- Go to Apps
- Click Install
- Search and install Simple-torrent

or

- Access via ssh
- Perform `sudo yunohost app install simple-torrent`

I've tried in both cases to keep default values and editing them.

**Expected behavior**
Installation of the App

**Logs**
https://paste.yunohost.org/raw/qufenipomu

Sorry for the Italian, the error translate to: "Error in installation script", and the first warning appears after the line "Setting up source files...", then grep and wget launch errors.

**Comment by ericgaspar** [comment]
My guess is that you arch processor is not supported. What is the output of `uname -m`?
 Simple-Torrent provides binaries for ARM64, X86 and i386 architecture.
That said, The app should provide a more elegant way to warn about this incompatibility 😅.

**Comment by Omnia89** [comment]
> My guess is that you arch processor is not supported. What is the output of uname -m?

armv7l

My bad, I didn't remember that that my minipc had a 32bit arch 😅 
Anyway, thanks for the answer!

I think I will stick with the good ol' transmission 😉
