### ISSUE TITLE
Yunohost 4.X not supported anymore ?

### ISSUE THREAD

**Issue by raphaeljolivet** [YunoHost-Apps/simple-torrent_ynh#74]
Hi, 

I am running Yunohost 4.3.6.2.
Simple Torrent is proposed in the list of applications I can install.

The admin panel pretends it starts intalling version "1.3.9~ynh4"

![image](https://user-images.githubusercontent.com/1201600/199507857-38b4feb1-4561-43fa-8ffc-8c3d6f3606ed.png)

But then the installation failed saying I don't have Yunohost 11.

![image](https://user-images.githubusercontent.com/1201600/199508053-826b23c7-a6f1-4eb6-89da-1cd0db18cf5d.png)

I saw on github that this packaging used to be compatible with Yunohost 4.X.
It seems backward compatibility is broken.

I am not sure how the version are handled in Yunohost packaging ?
Are you supposed to maintain a separate branch ?

**Comment by ericgaspar** [comment]
It is complicated to maintain backward compatibility... CI as migrated to 11.0 and there as been a lot of change and improvement in the helpers (not mentioning app package soon shifting to v2...).
Bref, I encourage you to update your server
